name: helpcare
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  pin_code_fields: ^8.0.1
  animate_do: ^4.2.0
  easy_localization: ^3.0.5
  dotted_border: ^3.1.0
  audio_wave: ^0.1.4
  google_maps_flutter: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  fl_chart: ^1.1.1
  http: ^1.2.2
  crypto: ^3.0.6
  shared_preferences: any
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  url_launcher: ^6.3.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^17.2.2
  flutter_reactive_ble: ^5.2.0
  permission_handler: ^11.3.1
  mobile_scanner: ^7.1.2
  local_auth: ^2.3.0
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^10.1.3
  qr_flutter: ^4.1.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  kakao_flutter_sdk: ^1.10.0
  kakao_flutter_sdk_user: ^1.10.0
  sqflite_common_ffi_web: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appIcon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lang/lang.csv
    - docs/btstep.png
  fonts:
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
